version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=task_system_db
      - MYSQL_ROOT_PASSWORD=root
  flyway:
    image: flyway/flyway:latest
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      - mysql
  api:
    build: ./
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/task_system_db
    depends_on:
      - mysql

#    environment:
#      - MYSQL_ROOT_PASSWORD=root
#      - MYSQL_DATABASE=database
#      - MYSQL_USER=root
#      - MYSQL_PASSWORD=root
#      my_sql_username: mysql
#      my_sql_pass: root
#      my_sql_taskmanagementsystem_url: jdbc:mysql://localhost:3306/task_system_db
#      my_sql_db: task_system_db


